In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
#vocabulary size
voc_size=10000

In [7]:
onehot_rep=[one_hot(words,voc_size)for words in sent]
print(onehot_rep)

[[6740, 8753, 3544, 203], [6740, 8753, 3544, 5409], [6740, 4433, 3544, 4817], [2457, 3993, 7544, 7578, 4629], [2457, 3993, 7544, 7578, 1790], [3754, 6740, 9864, 3544, 3591], [3602, 7061, 7599, 7578]]


In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np
sent_length=8
embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)

In [15]:
print(embedded_docs)


[[   0    0    0    0 6740 8753 3544  203]
 [   0    0    0    0 6740 8753 3544 5409]
 [   0    0    0    0 6740 4433 3544 4817]
 [   0    0    0 2457 3993 7544 7578 4629]
 [   0    0    0 2457 3993 7544 7578 1790]
 [   0    0    0 3754 6740 9864 3544 3591]
 [   0    0    0    0 3602 7061 7599 7578]]


In [16]:
dim=10

In [22]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.build(input_shape=(None,8))

In [23]:
model.summary()


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
[[[-9.7601637e-03 -3.8960122e-02  2.7556743e-02 -1.8914986e-02
    1.6395953e-02  4.2137276e-02 -3.4882534e-02  3.5866905e-02
    7.5852871e-04 -2.9063046e-02]
  [-9.7601637e-03 -3.8960122e-02  2.7556743e-02 -1.8914986e-02
    1.6395953e-02  4.2137276e-02 -3.4882534e-02  3.5866905e-02
    7.5852871e-04 -2.9063046e-02]
  [-9.7601637e-03 -3.8960122e-02  2.7556743e-02 -1.8914986e-02
    1.6395953e-02  4.2137276e-02 -3.4882534e-02  3.5866905e-02
    7.5852871e-04 -2.9063046e-02]
  [-9.7601637e-03 -3.8960122e-02  2.7556743e-02 -1.8914986e-02
    1.6395953e-02  4.2137276e-02 -3.4882534e-02  3.5866905e-02
    7.5852871e-04 -2.9063046e-02]
  [-4.9586009e-02 -3.9690316e-02  3.8423453e-02  7.0397258e-03
   -2.6581561e-02  3.7864596e-04 -4.1073121e-02  1.7651331e-02
   -1.0030866e-03  2.7319063e-02]
  [ 3.9003972e-02  2.8700959e-02  2.6817355e-02  4.6632174e-02
   -4.0591180e-02 -3.9860595e-02 -3.1183077e-02 -4.2369138e-02
   -3.1429425e-02  1.5830193e-02]
 